export const SAMPLE_LISTINGS = [
  {
    id:  1,
    title: "Spacious Modern House in Downtown Gandhinagar",
    location: "193/2, Sector 27, Gandhinagar",
    price: 12000,
    beds: 2,
    baths: 2,
    sqft: 1200,
    type: "House",
    images: [
      "/images/house.png",
    ],
  },
  {
    id: 2,
    title: "Luxurious Villa with Modern Amenities",
    location: "Infocity, Gandhinagar",
    price: 100000,
    beds: 5,
    baths: 4,
    sqft: 1600,
    type: "Villa",
    images: [
      "/images/villa.png",
    ],
  },
  {
    id: 3,
    title: "Affordable 4-Bedroom Flat in Sargasan",
    location: "Sargasan, Gandhinagar",
    price: 15000,
    beds: 4,
    baths: 3,
    sqft: 1400,
    type: "Flat",
    images: [
      "/images/flate.png",
    ],
  },
  {
    id: 4,
    title: "Luxury Penthouse with Scenic Views",
    location: "1045/2, Sector 6, Gandhinagar",
    price: 30000,
    beds: 7,
    baths: 3,
    sqft: 1800,
    type: "Penthouse",
    images: [
      "/images/penthouse.jpg",
    ],
  },
    {
      id: 5,
      title: "Spacious Downtown Villa",
      location: "333, Sector 5, Gandhinagar, Gujarat",
      price: 70000,
      beds: 2,
      baths: 1,
      featured: true,
      sqft: 1500,
      type: "Villa",
      images: ["/images/villa2.png"],
    },
    {
      id: 6,
      title: "Economy Studio Apartment",
      location: "222, Sector 6, Gandhinagar, Gujarat",
      price: 50000,
      beds: 1,
      baths: 1,
      featured: false,
      sqft: 700,
      type: "Apartment",
      images: ["/images/apartment3.png"],
    },
    {
      id: 7,
      title: "Single Family Home",
      location: "456, Sector 7, Gandhinagar, Gujarat",
      price: 30000,
      beds: 3,
      baths: 2,
      featured: false,
      sqft: 1800,
      type: "House",
      images: ["/images/house1.png"],
    },
    {
      id: 8,
      title: "Modern Family Villa",
      location: "77, Sector 8, Gandhinagar, Gujarat",
      price: 100000,
      beds: 4,
      baths: 3,
      featured: false,
      sqft: 2800,
      type: "Villa",
      images: ["/images/villa3.png"],
    },
    {
      id: 9,
      title: "Penthouse with City View",
      location: "555, Sector 9, Gandhinagar, Gujarat",
      price: 60000,
      beds: 2,
      baths: 2,
      featured: true,
      sqft: 1400,
      type: "Penthouse",
      images: ["/images/penthouse.jpg"],
    },
    {
      id: 10,
      title: "Private Luxury Villa",
      location: "89, Sector 10, Gandhinagar, Gujarat",
      price: 190000,
      beds: 6,
      baths: 5,
      featured: true,
      sqft: 5000,
      type: "Villa",
      images: ["/images/villa4.png"],
    },
    {
      id: 11,
      title: "Lavish Penthouse Suite",
      location: "1, Sector 11, Gandhinagar, Gujarat",
      price: 90000,
      beds: 4,
      baths: 4,
      featured: false,
      sqft: 4000,
      type: "Penthouse",
      images: ["/images/penthouse1.jpg"],
    },
    {
      id: 12,
      title: "Modern Private Apartment",
      location: "123, Sector 12, Gandhinagar, Gujarat",
      price: 60000,
      beds: 2,
      baths: 2,
      featured: true,
      sqft: 1100,
      type: "Apartment",
      images: ["/images/apartment4.png"],
    },
    {
      id: 13,
      title: "Charming Suburban House",
      location: "45, Sector 13, Gandhinagar, Gujarat",
      price: 50000,
      beds: 3,
      baths: 3,
      featured: true,
      sqft: 1700,
      type: "House",
      images: ["/images/house2.png"],
    },
  ];